/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsGithubRouteImport } from './routes/settings/github'
import { Route as DebugStoreRouteImport } from './routes/debug/store'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGithubRoute = SettingsGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => SettingsRoute,
} as any)
const DebugStoreRoute = DebugStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DebugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/debug/store': typeof DebugStoreRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/debug/store': typeof DebugStoreRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/debug/store': typeof DebugStoreRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/settings'
    | '/debug/store'
    | '/settings/github'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debug' | '/debug/store' | '/settings/github' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/settings'
    | '/debug/store'
    | '/settings/github'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/github': {
      id: '/settings/github'
      path: '/github'
      fullPath: '/settings/github'
      preLoaderRoute: typeof SettingsGithubRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/debug/store': {
      id: '/debug/store'
      path: '/store'
      fullPath: '/debug/store'
      preLoaderRoute: typeof DebugStoreRouteImport
      parentRoute: typeof DebugRoute
    }
  }
}

interface DebugRouteChildren {
  DebugStoreRoute: typeof DebugStoreRoute
}

const DebugRouteChildren: DebugRouteChildren = {
  DebugStoreRoute: DebugStoreRoute,
}

const DebugRouteWithChildren = DebugRoute._addFileChildren(DebugRouteChildren)

interface SettingsRouteChildren {
  SettingsGithubRoute: typeof SettingsGithubRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGithubRoute: SettingsGithubRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
